

doctoc:
	doctoc composants_applicatifs.md --github --title '**Index**'
	doctoc composants_infrastructure.md --github --title '**Index**'
	doctoc creation_espace_utilisateur.md --github --title '**Index**'
	doctoc deploiement.md --github --title '**Index**'
	doctoc utilisation_directe.md --github --title '**Index**'
	doctoc utilisation_spark_operator.md --github --title '**Index**'
#	doctoc ensuite.md --github --title '**Index**'

